[Distribution]
Distribution=ubuntu
Release=noble

[Output]
Format=disk
Output=disk
OutputDirectory=/output
Seed=11111111-2222-3333-4444-555555555555

[Content]
BaseTrees=/input/rootfs.tar
ExtraTrees=/config/extra
Initrds=/input/initrd.img
SourceDateEpoch=1722470400
Packages=
Bootable=yes
Bootloader=systemd-boot
KernelModulesInitrd=no
KernelCommandLine=root=LABEL=root-x86-64 rw console=ttyS0
