flush ruleset

table inet ale {
    chain output {
        type filter hook output priority 0;
        policy drop;
        oifname "lo" accept
        ct state established,related accept
        ip daddr 172.30.0.1 accept
    }
}
