"""Locking and materialising kits.

Hashing is a tool's job, not a contributor's. ``ale kit lock`` walks a repository's
kits, hashes each one's contents, and writes the lock that task manifests resolve
against — so a task references a kit by name and the exact bytes that ran end up in
provenance without anyone typing a digest.
"""

from __future__ import annotations

import hashlib
import tomllib
from pathlib import Path

import yaml

from ale.core.errors import TaskDefinitionError
from ale.core.ids import content_hash
from ale.core.kit import KitManifest, KitsLock, LockedKit

__all__ = ["KITS_DIR", "LOCK_FILE", "hash_kit", "read_lock", "scan_kits", "write_lock"]

KITS_DIR = "kits"
LOCK_FILE = "kits.lock.yaml"
MANIFEST = "kit.toml"

#: Ignored when hashing: caches say nothing about what the kit does.
_IGNORED = {"__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}


def hash_kit(directory: Path) -> str:
    """Hash a kit's contents.

    Paths are included alongside file bytes, so moving a file changes the hash — a kit
    is its layout as much as its text.
    """
    entries: list[tuple[str, str]] = []
    for path in sorted(directory.rglob("*")):
        if not path.is_file() or any(part in _IGNORED for part in path.parts):
            continue
        digest = hashlib.sha256(path.read_bytes()).hexdigest()
        entries.append((str(path.relative_to(directory)), digest))
    return content_hash(entries)


def read_manifest(directory: Path) -> KitManifest:
    path = directory / MANIFEST
    if not path.is_file():
        raise TaskDefinitionError(f"{directory} has no {MANIFEST}")
    with path.open("rb") as handle:
        return KitManifest.model_validate(tomllib.load(handle))


def scan_kits(repo_root: Path) -> KitsLock:
    """Build the lock a repository's kits currently imply."""
    kits_dir = repo_root / KITS_DIR
    if not kits_dir.is_dir():
        return KitsLock()

    locked: list[LockedKit] = []
    for directory in sorted(kits_dir.iterdir()):
        if not directory.is_dir() or not (directory / MANIFEST).is_file():
            continue
        manifest = read_manifest(directory)
        if manifest.name != directory.name:
            raise TaskDefinitionError(
                f"kit {manifest.name!r} lives in {directory.name!r}; a kit's directory is "
                f"how it is found at materialisation time, so the two must match"
            )
        locked.append(
            LockedKit(
                name=manifest.name,
                package=manifest.package,
                content_hash=hash_kit(directory),
                python_min=manifest.python_min,
                runtime=manifest.runtime,
            )
        )
    return KitsLock(kits=tuple(locked))


def read_lock(repo_root: Path) -> KitsLock:
    path = repo_root / LOCK_FILE
    if not path.is_file():
        return KitsLock()
    loaded = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    return KitsLock.model_validate(loaded)


def write_lock(repo_root: Path, lock: KitsLock) -> Path:
    path = repo_root / LOCK_FILE
    payload = lock.model_dump(mode="json")
    header = (
        "# Generated by `ale kit lock`. Do not edit.\n"
        "#\n"
        "# Task manifests reference kits by name; this file pins what those names\n"
        "# resolved to, and the hashes land in every run's provenance record.\n"
    )
    path.write_text(header + yaml.safe_dump(payload, sort_keys=True), encoding="utf-8")
    return path
