"""Kits: shared Python systems injected into a sandbox.

A domain's tasks rarely share a shell script; they share a *library* — a grader
protocol, a scoring toolkit, a simulation adapter. This is the capability the previous
generation of harnesses lacked, and the one we deliberately add.

The hard constraint is that a kit must land in a sandbox **whose interpreter we do not
choose**: old ROS images ship Python 3.8, conda images ship their own environment. So a
kit is materialised by copying its package to where that interpreter already searches,
asked of the interpreter rather than assumed. No pip install, no network, no touching the
image's package manager, and no search path of our own — an engine-specific one is a rule
every task author has to learn, and ours was silently wrong for as long as it existed.

The destination is the system location rather than any one account's: stages run as the
framework and the agent runs unprivileged, so a kit in either one's private site-packages
is importable for that identity and missing for the other.

A stdlib-only kit therefore works everywhere; a kit with dependencies declares them and
the image must already provide them, which is checked with an import probe rather than
assumed.

Versions are content hashes, generated by tooling and recorded in ``kits.lock.yaml``.
A task references a kit by name only — contributors never type a hash.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

__all__ = ["KitManifest", "KitRuntime", "KitsLock", "LockedKit"]


class KitRuntime(StrEnum):
    """What a kit needs from the image it lands in."""

    STDLIB = "stdlib"
    """Imports nothing outside the standard library. Works in any image."""

    IMAGE_DEPS = "image_deps"
    """Needs packages the image must already provide; verified by an import probe."""


class KitManifest(BaseModel):
    """``kit.toml`` — what a kit is and what it needs.

    Authored once per kit and rarely touched again; everything version-related is
    generated.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str = Field(description="Kit name, referenced from task manifests")
    package: str = Field(description="Import name, which may differ from the kit name")
    description: str = ""
    python_min: str = Field(default="3.8", description="Lowest guest interpreter supported")
    runtime: KitRuntime = KitRuntime.STDLIB
    requires: tuple[str, ...] = Field(
        default=(), description="Import names the image must provide when runtime is image_deps"
    )
    entry: str | None = Field(default=None, description="Optional module to execute")

    def import_probe(self) -> str:
        """A one-liner that fails loudly if the kit cannot be imported in the guest."""
        modules = [self.package, *self.requires]
        imports = ", ".join(modules)
        return f"import {imports}"

    # --- validation ---

    @model_validator(mode="after")
    def _check_requirements(self) -> Self:
        if self.runtime is KitRuntime.STDLIB and self.requires:
            raise ValueError("a stdlib kit cannot declare requirements; set runtime to image_deps")
        if self.runtime is KitRuntime.IMAGE_DEPS and not self.requires:
            raise ValueError("an image_deps kit must list what the image has to provide")
        return self


class LockedKit(BaseModel):
    """A kit pinned by content, as recorded in ``kits.lock.yaml``."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    name: str
    package: str
    content_hash: str = Field(pattern=r"^sha256:[0-9a-f]{64}$")
    python_min: str = "3.8"
    runtime: KitRuntime = KitRuntime.STDLIB


class KitsLock(BaseModel):
    """Generated inventory of a task repository's kits.

    Regenerated by ``ale kit lock`` and checked in CI, so a kit's contents and the hash
    recorded in a run's provenance cannot drift apart.
    """

    model_config = ConfigDict(frozen=True, extra="forbid")

    schema_version: int = 1
    kits: tuple[LockedKit, ...] = ()

    def get(self, name: str) -> LockedKit | None:
        return next((kit for kit in self.kits if kit.name == name), None)

    def require(self, name: str) -> LockedKit:
        kit = self.get(name)
        if kit is None:
            known = ", ".join(sorted(k.name for k in self.kits)) or "none"
            raise KeyError(f"unknown kit {name!r}; locked kits: {known}")
        return kit
